version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funlen
    - godox
    - gomoddirectives
    - ireturn # we be enabled again with v2
    - noinlineerr
    - nlreturn
    - nonamedreturns
    - paralleltest
    - recvcheck
    - testpackage
    - tparallel
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 3
    cyclop:
      max-complexity: 20
    gocyclo:
      min-complexity: 20
    exhaustive:
      default-signifies-exhaustive: true
      default-case-required: true
    lll:
      line-length: 180
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: false  # disable for testing.TB - asserter callbacks don't need tb.Helper()
      fuzz:
        first: true
        name: true
        begin: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
