name: Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        go_version: ['1.19','oldstable','stable']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}
        check-latest: true

    - name: Tests
      run: go test -v -race -cover -coverprofile=coverage.out -covermode=atomic ./...


    - name: Update Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
        parallel: true

  finish:
    name: 'Complete test coverage upload'
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
